package org.pahappa.systems.egoSms.core.webControllers;
import com.fasterxml.jackson.databind.ObjectMapper;import org.pahappa.systems.egoSms.core.services.impl.whatsapp.MetaConfiguration;import org.pahappa.systems.egoSms.core.services.whatsapp.*;import org.pahappa.systems.egoSms.models.whatsapp.WhatsappConnection;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.http.*;import org.springframework.stereotype.Controller;import org.springframework.web.bind.annotation.*;import java.util.*;
@Controller @RequestMapping("/whatsapp/signup")
public class WhatsappSignupController{
 private final ObjectMapper mapper=new ObjectMapper();@Autowired private WhatsappSignupService signup;@Autowired private WhatsappConnectionService connections;@Autowired private MetaConfiguration config;
 @RequestMapping(value="/configuration",method=RequestMethod.GET) @ResponseBody public ResponseEntity<String> configuration(){try{Map<String,String> data=new LinkedHashMap<String,String>();data.put("appId",config.appId());data.put("configId",config.signupConfigId());data.put("apiVersion",config.version());return response(data,HttpStatus.OK);}catch(Exception e){return response(Collections.singletonMap("message",root(e)),HttpStatus.INTERNAL_SERVER_ERROR);}}
 @RequestMapping(value="/connections",method=RequestMethod.GET) @ResponseBody public String connections(){List<Map<String,Object>> data=new ArrayList<Map<String,Object>>();for(WhatsappConnection c:connections.getLoggedInUserConnections())data.add(dto(c));return json(data);}
 @RequestMapping(value="/complete",method=RequestMethod.POST) @ResponseBody public ResponseEntity<String> complete(@RequestParam("code")String code,@RequestParam(value="businessId",required=false)String businessId,@RequestParam("wabaId")String wabaId,@RequestParam("phoneNumberId")String phoneNumberId){try{return response(dto(signup.complete(code,businessId,wabaId,phoneNumberId)),HttpStatus.OK);}catch(Exception e){return response(Collections.singletonMap("message",root(e)),HttpStatus.BAD_REQUEST);}}
 private Map<String,Object> dto(WhatsappConnection c){Map<String,Object> m=new LinkedHashMap<String,Object>();m.put("id",c.getId());m.put("businessId",c.getBusinessId());m.put("wabaId",c.getWabaId());m.put("phoneNumberId",c.getPhoneNumberId());m.put("displayPhoneNumber",c.getDisplayPhoneNumber());m.put("verifiedName",c.getVerifiedName());m.put("status",c.getConnectionStatus());return m;}
 private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("Could not create JSON response",e);}}
 private ResponseEntity<String> response(Object value,HttpStatus status){HttpHeaders headers=new HttpHeaders();headers.setContentType(MediaType.APPLICATION_JSON);return new ResponseEntity<String>(json(value),headers,status);}
 private String root(Throwable error){Throwable value=error;while(value.getCause()!=null)value=value.getCause();return value.getMessage()==null?value.toString():value.getMessage();}
}
